name: Bump version on main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure git author
        uses: MaxiGarcia13/gh-actions/.github/actions/configure-git-author@main
        with:
          user_name: github-actions[bot]
          user_email: github-actions[bot]@users.noreply.github.com

      - name: Bump version
        uses: MaxiGarcia13/gh-actions/.github/workflows/bump-version.yml@main
